version: 2.1
jobs:
  build:
    docker:
      - image: maven:3.8-jdk-17

    working_directory: /app

    steps:
      - checkout

      - run:
          name: Build and Test
          command: mvn test

      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/site/jacoco

workflows:
  version: 2
  test:
    jobs:
      - build
